### ISSUE TITLE
13 Errors

### ISSUE THREAD

**Issue by JedsonVelocity** [ceifa/deathrun#13]
I receive the attached 13 errors when trying to use this gamemode.
![image](https://user-images.githubusercontent.com/113303680/189539633-086a39f1-a85c-421e-9716-a7f8c8914bbe.png)

**Comment by ceifa** [comment]
Since facepunch changes this game a lot, it probably is broke. I will take a look on it later.

**Comment by JedsonVelocity** [comment]
thanks ceifa, i'm looking forward to it! :)

**Comment by ceifa** [comment]
Fixed, just reinstall the addon

**Comment by JedsonVelocity** [comment]
thanks ceifa! :)
